### ISSUE TITLE
Does not install on Yosemite

### ISSUE THREAD

**Issue by woganmay** [anandthakker/atom-node-debug#17]
I'm not sure whether it's related to Yosemite, or some other misconfiguration on my system, but I am unable to install this:

    > ws@0.4.32 install /private/var/folders/s2/dbg59ngs2zj4cwh11x5hkzbr0000gp/T/apm-install-dir-11519-11086-c4ubl8/node_modules/debugger/node_modules/ws
    > (node-gyp rebuild 2> builderror.log) || (exit 0)    

      CXX(target) Release/obj.target/bufferutil/src/bufferutil.o    

    > runas@1.1.0 install /private/var/folders/s2/dbg59ngs2zj4cwh11x5hkzbr0000gp/T/apm-install-dir-11519-11086-c4ubl8/node_modules/debugger/node_modules/text-buffer/node_modules/pathwatcher/node_modules/runas
    > node-gyp rebuild    

      CXX(target) Release/obj.target/runas/src/main.o    

    In file included from ../src/main.cc:1:
    ../../nan/nan.h:623:19: error: no type named 'ExternalAsciiStringResource' in 'v8::String'; did you mean 'ExternalStringResource'?
          v8::String::ExternalAsciiStringResource *resource) {
          ~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~
                      ExternalStringResource
    /Users/wmay/.atom/.node-gyp/.node-gyp/0.21.0/deps/v8/include/v8.h:1936:19: note: 'ExternalStringResource' declared here
      class V8_EXPORT ExternalStringResource
                      ^
    In file included from ../src/main.cc:1:
    ../../nan/nan.h:622:36: error: redefinition of 'NanNew'
      NAN_INLINE v8::Local<v8::String> NanNew(
                                       ^
    ../../nan/nan.h:617:36: note: previous definition is here
      NAN_INLINE v8::Local<v8::String> NanNew(
                                       ^
    ../../nan/nan.h:1993:12: error: no member named 'IsExternalAscii' in 'v8::String'; did you mean 'IsExternal'?
      if (str->IsExternalAscii()) {
               ^~~~~~~~~~~~~~~
               IsExternal
    /Users/wmay/.atom/.node-gyp/.node-gyp/0.21.0/deps/v8/include/v8.h:1900:8: note: 'IsExternal' declared here
      bool IsExternal() const;
           ^
    In file included from ../src/main.cc:1:
    ../../nan/nan.h:1994:23: error: no type named 'ExternalAsciiStringResource' in 'v8::String'; did you mean 'ExternalStringResource'?
        const v8::String::ExternalAsciiStringResource* ext;
              ~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~
                          ExternalStringResource
    /Users/wmay/.atom/.node-gyp/.node-gyp/0.21.0/deps/v8/include/v8.h:1936:19: note: 'ExternalStringResource' declared here
      class V8_EXPORT ExternalStringResource
                      ^
    In file included from ../src/main.cc:1:
    ../../nan/nan.h:1995:16: error: no member named 'GetExternalAsciiStringResource' in 'v8::String'; did you mean 'GetExternalOneByteStringResource'?
        ext = str->GetExternalAsciiStringResource();
                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                   GetExternalOneByteStringResource
    /Users/wmay/.atom/.node-gyp/.node-gyp/0.21.0/deps/v8/include/v8.h:2003:40: note: 'GetExternalOneByteStringResource' declared here
      const ExternalOneByteStringResource* GetExternalOneByteStringResource() const;
                                           ^
    In file included from ../src/main.cc:1:
    ../../nan/nan.h:1995:9: error: assigning to 'const v8::String::ExternalStringResource *' from incompatible type 'const v8::String::ExternalOneByteStringResource *'
        ext = str->GetExternalAsciiStringResource();
            ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    ../../nan/nan.h:1996:11: error: assigning to 'const char *' from incompatible type 'const uint16_t *' (aka 'const unsigned short *')
        *data = ext->data();
              ^ ~~~~~~~~~~~
    7 errors generated.
    make: *** [Release/obj.target/runas/src/main.o] Error 1
    gyp ERR! build error 
    gyp ERR! stack Error: `make` failed with exit code: 2
    gyp ERR! stack     at ChildProcess.onExit (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
    gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
    gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
    gyp ERR! System Darwin 14.1.0
    gyp ERR! command "node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
    gyp ERR! cwd /private/var/folders/s2/dbg59ngs2zj4cwh11x5hkzbr0000gp/T/apm-install-dir-11519-11086-c4ubl8/node_modules/debugger/node_modules/text-buffer/node_modules/pathwatcher/node_modules/runas
    gyp ERR! node -v v0.10.35
    gyp ERR! node-gyp -v v1.0.2
    gyp ERR! not ok 
    npm ERR! Darwin 14.1.0
    npm ERR! argv "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Applications/Atom.app/Contents/Resources/app/apm/.apmrc" "--userconfig" "/Users/wmay/.atom/.apmrc" "install" "/private/var/folders/s2/dbg59ngs2zj4cwh11x5hkzbr0000gp/T/d-11519-11086-1h1aka8/package.tgz" "--target=0.21.0" "--arch=x64"
    npm ERR! node v0.10.35
    npm ERR! npm  v2.3.0
    npm ERR! code ELIFECYCLE    

    npm ERR! runas@1.1.0 install: `node-gyp rebuild`
    npm ERR! Exit status 1
    npm ERR! 
    npm ERR! Failed at the runas@1.1.0 install script 'node-gyp rebuild'.
    npm ERR! This is most likely a problem with the runas package,
    npm ERR! not with npm itself.
    npm ERR! Tell the author that this fails on your system:
    npm ERR!     node-gyp rebuild
    npm ERR! You can get their info via:
    npm ERR!     npm owner ls runas
    npm ERR! There is likely additional logging output above.    

    npm ERR! Please include the following file with any support request:
    npm ERR!     /private/var/folders/s2/dbg59ngs2zj4cwh11x5hkzbr0000gp/T/apm-install-dir-11519-11086-c4ubl8/npm-debug.log

**Comment by bharathrao** [comment]
I have the same issue. This is a Nan incompatibility common to many packages: https://www.google.com/search?q=no+type+named+%27ExternalAsciiStringResource%27

**Comment by Queuecumber** [comment]
Also having the same issue on Ubuntu

**Comment by jameswomack** [comment]
+1

**Comment by pvssvikas** [comment]
same here +1 at Atom Version 0.187.0 (0.187.0); and OS X Yosemite

**Comment by kaanyilgin** [comment]
+1 at Atom Version 0.187.0 and on Win

**Comment by SMG008** [comment]
Doesn't install on Win :+1: 

> ws@0.4.32 install C:\Users\SOUVIK~1\AppData\Local\Temp\apm-install-dir-115224-11092-x2t1gm\node_modules\debugger\node_modules\ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)


C:\Users\SOUVIK~1\AppData\Local\Temp\apm-install-dir-115224-11092-x2t1gm\node_modules\debugger\node_modules\ws>node "C:\Users\souvik_ghosh\AppData\Local\atom\app-0.187.0\resources\app\apm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild 

> runas@1.1.0 install C:\Users\SOUVIK~1\AppData\Local\Temp\apm-install-dir-115224-11092-x2t1gm\node_modules\debugger\node_modules\text-buffer\node_modules\pathwatcher\node_modules\runas
> node-gyp rebuild


C:\Users\SOUVIK~1\AppData\Local\Temp\apm-install-dir-115224-11092-x2t1gm\node_modules\debugger\node_modules\text-buffer\node_modules\pathwatcher\node_modules\runas>node "C:\Users\souvik_ghosh\AppData\Local\atom\app-0.187.0\resources\app\apm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild 

gypnpm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Users\\souvik_ghosh\\AppData\\Local\\atom\\app-0.187.0\\resources\\app\\apm\\bin\\\\node.exe" "C:\\Users\\souvik_ghosh\\AppData\\Local\\atom\\app-0.187.0\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\souvik_ghosh\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\souvik_ghosh\\.atom\\.apmrc" "install" "C:\\Users\\SOUVIK~1\\AppData\\Local\\Temp\\d-115224-11092-1x0j02r\\package.tgz" "--target=0.21.0" "--arch=ia32" "--msvs_version=2013"
npm ERR! node v0.10.35
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE

npm ERR! runas@1.1.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the runas@1.1.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the runas package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls runas
npm ERR! There is likely additional logging output above.

**Comment by anandthakker** [comment]
Alas, this package is just too far behind, so I'm officially stopping active development.   Here's a similar one that's active: https://github.com/kiddkai/atom-node-debugger  (atom package: https://atom.io/packages/node-debugger)
